# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7cbb6fde8237b9619dad3733c8541c1dae5b5e8d4af46a66d37f71900fc979e4bbc970bb6c248c59a872fa79e99fb06bd8f5757d5111e7c3cd09220b655a4c3

test:
  secret_key_base: d803dc68056565a8db8b9716a6ee1ffda1a8594667f4982b42414835abbc04c01ad8455fb8ad18ca0ce39f4998f257119769c81b14d25409d9251a498646896a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
